TMPro::TMP_TextEventHandler
CharacterSelectionEvent TMPro.TMP_TextEventHandler.onCharacterSelection
Event delegate triggered when pointer is over a character.
Referenced by TMPro.TMP_TextEventHandler.SendOnCharacterSelection.
SpriteSelectionEvent TMPro.TMP_TextEventHandler.onSpriteSelection
Event delegate triggered when pointer is over a sprite.
Referenced by TMPro.TMP_TextEventHandler.SendOnSpriteSelection.
WordSelectionEvent TMPro.TMP_TextEventHandler.onWordSelection
Event delegate triggered when pointer is over a word.
Referenced by TMPro.TMP_TextEventHandler.SendOnWordSelection.
LineSelectionEvent TMPro.TMP_TextEventHandler.onLineSelection
Event delegate triggered when pointer is over a line.
Referenced by TMPro.TMP_TextEventHandler.SendOnLineSelection.
LinkSelectionEvent TMPro.TMP_TextEventHandler.onLinkSelection
Event delegate triggered when pointer is over a link.
Referenced by TMPro.TMP_TextEventHandler.SendOnLinkSelection.
CharacterSelectionEvent TMPro.TMP_TextEventHandler.m_OnCharacterSelection
SpriteSelectionEvent TMPro.TMP_TextEventHandler.m_OnSpriteSelection
WordSelectionEvent TMPro.TMP_TextEventHandler.m_OnWordSelection
LineSelectionEvent TMPro.TMP_TextEventHandler.m_OnLineSelection
LinkSelectionEvent TMPro.TMP_TextEventHandler.m_OnLinkSelection
TMP_Text TMPro.TMP_TextEventHandler.m_TextComponent
Referenced by TMPro.TMP_TextEventHandler.Awake, TMPro.TMP_TextEventHandler.LateUpdate.
Camera TMPro.TMP_TextEventHandler.m_Camera
Referenced by TMPro.TMP_TextEventHandler.Awake, TMPro.TMP_TextEventHandler.LateUpdate.
Canvas TMPro.TMP_TextEventHandler.m_Canvas
Referenced by TMPro.TMP_TextEventHandler.Awake.
int TMPro.TMP_TextEventHandler.m_selectedLink
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
int TMPro.TMP_TextEventHandler.m_lastCharIndex
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
int TMPro.TMP_TextEventHandler.m_lastWordIndex
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
int TMPro.TMP_TextEventHandler.m_lastLineIndex
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
void TMPro.TMP_TextEventHandler.Awake()
References TMPro.TMP_TextEventHandler.m_Camera, TMPro.TMP_TextEventHandler.m_Canvas, TMPro.TMP_TextEventHandler.m_TextComponent.
void TMPro.TMP_TextEventHandler.LateUpdate()
References TMPro.TMP_TextEventHandler.m_Camera, TMPro.TMP_TextEventHandler.m_lastCharIndex, TMPro.TMP_TextEventHandler.m_lastLineIndex, TMPro.TMP_TextEventHandler.m_lastWordIndex, TMPro.TMP_TextEventHandler.m_selectedLink, TMPro.TMP_TextEventHandler.m_TextComponent, TMPro.TMP_TextEventHandler.SendOnCharacterSelection, TMPro.TMP_TextEventHandler.SendOnLineSelection, TMPro.TMP_TextEventHandler.SendOnLinkSelection, TMPro.TMP_TextEventHandler.SendOnSpriteSelection, TMPro.TMP_TextEventHandler.SendOnWordSelection.
void TMPro.TMP_TextEventHandler.SendOnCharacterSelection(char character, int characterIndex)
References TMPro.TMP_TextEventHandler.onCharacterSelection.
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
void TMPro.TMP_TextEventHandler.SendOnSpriteSelection(char character, int characterIndex)
References TMPro.TMP_TextEventHandler.onSpriteSelection.
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
void TMPro.TMP_TextEventHandler.SendOnWordSelection(string word, int charIndex, int length)
References TMPro.TMP_TextEventHandler.onWordSelection.
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
void TMPro.TMP_TextEventHandler.SendOnLineSelection(string line, int charIndex, int length)
References TMPro.TMP_TextEventHandler.onLineSelection.
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
void TMPro.TMP_TextEventHandler.SendOnLinkSelection(string linkID, string linkText, int linkIndex)
References TMPro.TMP_TextEventHandler.onLinkSelection.
Referenced by TMPro.TMP_TextEventHandler.LateUpdate.
void TMPro.TMP_TextEventHandler.OnPointerEnter(PointerEventData eventData)
void TMPro.TMP_TextEventHandler.OnPointerExit(PointerEventData eventData)