NvFractureTool
static void NvFractureTool._FractureTool_Release(IntPtr tool)
Referenced by Release.
static IntPtr NvFractureTool.NvBlastExtAuthoringCreateFractureTool()
Referenced by NvFractureTool.
static void NvFractureTool._FractureTool_setSourceMesh(IntPtr tool, IntPtr mesh)
Referenced by setSourceMesh.
static void NvFractureTool._FractureTool_setRemoveIslands(IntPtr tool, bool remove)
Referenced by setRemoveIslands.
static bool NvFractureTool._FractureTool_voronoiFracturing(IntPtr tool, int chunkId, IntPtr vsg)
Referenced by voronoiFracturing.
static bool NvFractureTool._FractureTool_slicing(IntPtr tool, int chunkId, [Out] SlicingConfiguration conf, bool replaceChunk)
Referenced by slicing.
static void NvFractureTool._FractureTool_finalizeFracturing(IntPtr tool)
Referenced by finalizeFracturing.
static int NvFractureTool._FractureTool_getChunkCount(IntPtr tool)
Referenced by getChunkCount.
static IntPtr NvFractureTool._FractureTool_getChunkMesh(IntPtr tool, int chunkId, bool inside)
Referenced by getChunkMesh.
NvFractureTool.NvFractureTool()
References DisposablePtr.Initialize, NvBlastExtAuthoringCreateFractureTool.
void NvFractureTool.setSourceMesh(NvMesh mesh)
References _FractureTool_setSourceMesh, DisposablePtr.ptr.
void NvFractureTool.setRemoveIslands(bool remove)
References _FractureTool_setRemoveIslands, DisposablePtr.ptr.
bool NvFractureTool.voronoiFracturing(int chunkId, NvVoronoiSitesGenerator vsg)
References _FractureTool_voronoiFracturing, DisposablePtr.ptr.
bool NvFractureTool.slicing(int chunkId, SlicingConfiguration conf, bool replaceChunk)
References _FractureTool_slicing, DisposablePtr.ptr.
void NvFractureTool.finalizeFracturing()
References _FractureTool_finalizeFracturing, DisposablePtr.ptr.
int NvFractureTool.getChunkCount()
References _FractureTool_getChunkCount, DisposablePtr.ptr.
NvMesh NvFractureTool.getChunkMesh(int chunkId, bool inside)
References _FractureTool_getChunkMesh, DisposablePtr.ptr.
override void NvFractureTool.Release()
References _FractureTool_Release, DisposablePtr.ptr.