NvVoronoiSitesGenerator
static void NvVoronoiSitesGenerator._VoronoiSitesGenerator_Release(IntPtr site)
Referenced by Release.
static IntPtr NvVoronoiSitesGenerator._VoronoiSitesGenerator_Create(IntPtr mesh)
Referenced by NvVoronoiSitesGenerator.
static IntPtr NvVoronoiSitesGenerator._NvVoronoiSitesGenerator_uniformlyGenerateSitesInMesh(IntPtr tool, int count)
Referenced by uniformlyGenerateSitesInMesh.
static IntPtr NvVoronoiSitesGenerator._NvVoronoiSitesGenerator_addSite(IntPtr tool, [In] Vector3 site)
Referenced by addSite.
static bool NvVoronoiSitesGenerator._NvVoronoiSitesGenerator_clusteredSitesGeneration(IntPtr tool, int numberOfClusters, int sitesPerCluster, float clusterRadius)
Referenced by clusteredSitesGeneration.
static int NvVoronoiSitesGenerator._NvVoronoiSitesGenerator_getSitesCount(IntPtr tool)
Referenced by getSitesCount.
static void NvVoronoiSitesGenerator._NvVoronoiSitesGenerator_getSites(IntPtr tool, [In, Out] Vector3[] arr)
Referenced by getSites.
NvVoronoiSitesGenerator.NvVoronoiSitesGenerator(NvMesh mesh)
References _VoronoiSitesGenerator_Create, DisposablePtr.Initialize, DisposablePtr.ptr.
void NvVoronoiSitesGenerator.uniformlyGenerateSitesInMesh(int count)
References _NvVoronoiSitesGenerator_uniformlyGenerateSitesInMesh, DisposablePtr.ptr.
void NvVoronoiSitesGenerator.addSite(Vector3 site)
References _NvVoronoiSitesGenerator_addSite, DisposablePtr.ptr.
Referenced by boneSiteGeneration.
void NvVoronoiSitesGenerator.clusteredSitesGeneration(int numberOfClusters, int sitesPerCluster, float clusterRadius)
References _NvVoronoiSitesGenerator_clusteredSitesGeneration, DisposablePtr.ptr.
Vector3 [] NvVoronoiSitesGenerator.getSites()
References _NvVoronoiSitesGenerator_getSites, getSitesCount, DisposablePtr.ptr.
int NvVoronoiSitesGenerator.getSitesCount()
References _NvVoronoiSitesGenerator_getSitesCount, DisposablePtr.ptr.
Referenced by getSites.
void NvVoronoiSitesGenerator.boneSiteGeneration(SkinnedMeshRenderer smr)
References addSite.
override void NvVoronoiSitesGenerator.Release()
References _VoronoiSitesGenerator_Release, DisposablePtr.ptr.