MeshCutter
bool MeshCutter.currentlyCutting
Referenced by Cut.
Mesh MeshCutter.originalMesh
Referenced by Cut, Fill.
GameObject MeshCutter.Cut(GameObject cutObject, Vector3 cutPoint, Vector3 cutDirection, bool enableGravityForNewMesh=true, bool canNewMeshShatter=false)
References currentlyCutting, CutTriangle, FillCut, LEFT, MIXED, originalMesh.
void MeshCutter.CutTriangle(Plane cutPlane, Triangle triangle, List< TriangleSide > sides, MeshData leftMesh, MeshData rightMesh, List< Vector3 > newVerts)
References Triangle.submeshIndex, TriangleIsValid, Triangle.vertices.
Referenced by Cut.
bool MeshCutter.TriangleIsValid(Triangle _triangle, Vector3[] _newVertices, Vector3[] _newNormals)
Referenced by CutTriangle, Fill.
void MeshCutter.FillCut(List< Vector3 > newVerts, Plane cutPlane, MeshData leftMesh, MeshData rightMesh)
References EvaluatePairs, Fill.
Referenced by Cut.
void MeshCutter.EvaluatePairs(List< Vector3 > newVerts, List< Vector3 > vertices, List< Vector3 > meshPoly)
Referenced by FillCut.
void MeshCutter.Fill(List< Vector3 > existingVerts, Plane cutPlane, MeshData leftMesh, MeshData rightMesh)
References originalMesh, TriangleIsValid.
Referenced by FillCut.