GK::DelaunayCalculator
int GK.DelaunayCalculator.highest
Referenced by GK.DelaunayCalculator.CalculateTriangulation, GK.DelaunayCalculator.LegalEdge, GK.DelaunayCalculator.RunBowyerWatson.
IList<Vector2> GK.DelaunayCalculator.verts
Referenced by GK.DelaunayCalculator.CalculateTriangulation, GK.DelaunayCalculator.GenerateResult, GK.DelaunayCalculator.Higher, GK.DelaunayCalculator.LegalEdge, GK.DelaunayCalculator.ToTheLeft.
List<int> GK.DelaunayCalculator.indices
Referenced by GK.DelaunayCalculator.DelaunayCalculator, GK.DelaunayCalculator.ShuffleIndices.
List<TriangleNode> GK.DelaunayCalculator.triangles
Referenced by GK.DelaunayCalculator.DelaunayCalculator, GK.DelaunayCalculator.FindTriangleNode, GK.DelaunayCalculator.GenerateResult, GK.DelaunayCalculator.LeafWithEdge, GK.DelaunayCalculator.LegalizeEdge, GK.DelaunayCalculator.PointInTriangle, GK.DelaunayCalculator.RunBowyerWatson.
GK.DelaunayCalculator.DelaunayCalculator()
Creates a new Delaunay triangulation calculator
References GK.DelaunayCalculator.indices, GK.DelaunayCalculator.triangles.
DelaunayTriangulation GK.DelaunayCalculator.CalculateTriangulation(IList< Vector2 > verts)
Calculate the triangulation of the supplied vertices
verts List of vertices to use for calculation The calculated Delaunay triangulation<returns>
void GK.DelaunayCalculator.CalculateTriangulation(IList< Vector2 > verts, ref DelaunayTriangulation result)
Calculate the triangulation of the supplied vertices.
This overload allows you to reuse the result object, to prevent garbage from being created. verts List of vertices to use for calculation result Result object to store the triangulation in
References GK.DelaunayCalculator.GenerateResult, GK.DelaunayCalculator.Higher, GK.DelaunayCalculator.highest, GK.DelaunayCalculator.RunBowyerWatson, GK.DelaunayCalculator.verts.
bool GK.DelaunayCalculator.Higher(int pi0, int pi1)
References GK.DelaunayCalculator.verts.
Referenced by GK.DelaunayCalculator.CalculateTriangulation, GK.DelaunayCalculator.ToTheLeft.
void GK.DelaunayCalculator.RunBowyerWatson()
Run the algorithm
References GK.DelaunayCalculator.FindTriangleNode, GK.DelaunayCalculator.highest, GK.DelaunayCalculator.LegalizeEdge, GK.DelaunayCalculator.triangles.
Referenced by GK.DelaunayCalculator.CalculateTriangulation.
void GK.DelaunayCalculator.GenerateResult(ref DelaunayTriangulation result)
Filter the points array and triangle tree into a readable result.
References GK.DelaunayCalculator.triangles, GK.DelaunayCalculator.verts.
Referenced by GK.DelaunayCalculator.CalculateTriangulation.
void GK.DelaunayCalculator.ShuffleIndices()
Shuffle the indices array. Optimal runtime depends on shuffled input.
References GK.DelaunayCalculator.indices.
int GK.DelaunayCalculator.LeafWithEdge(int ti, int e0, int e1)
Find the leaf of the triangles[ti] subtree that contains a given edge.
We need this because when we split or flip triangles, the adjacency references don't update, so even if the adjacency triangles were leaves when the node was created, they might not be leaves later. If they aren't, they're going to be the ancestor of the correct leaf, so this method goes down the tree finding the right leaf.
References GK.DelaunayCalculator.triangles.
Referenced by GK.DelaunayCalculator.LegalizeEdge.
bool GK.DelaunayCalculator.LegalEdge(int k, int l, int i, int j)
Is the edge legal, or does it need to be flipped?
References GK.DelaunayCalculator.highest, GK.DelaunayCalculator.verts.
Referenced by GK.DelaunayCalculator.LegalizeEdge.
void GK.DelaunayCalculator.LegalizeEdge(int ti0, int ti1, int pi, int li0, int li1)
Key part of the algorithm. Flips edges if they need to be flipped, and recurses.
pi is the newly inserted point, creating a new triangle ti0. The adjacent triangle opposite pi in ti0 is ti1. The edge separating the two triangles is li0 and li1.Checks if the (li0, li1) edge needs to be flipped. If it does, creates two new triangles, and recurses to check if the newly created triangles need flipping.
References GK.DelaunayCalculator.LeafWithEdge, GK.DelaunayCalculator.LegalEdge, GK.DelaunayCalculator.triangles.
Referenced by GK.DelaunayCalculator.RunBowyerWatson.
int GK.DelaunayCalculator.FindTriangleNode(int pi)
Find the leaf triangle in the triangle tree containing a certain point.
References GK.DelaunayCalculator.PointInTriangle, GK.DelaunayCalculator.triangles.
Referenced by GK.DelaunayCalculator.RunBowyerWatson.
bool GK.DelaunayCalculator.PointInTriangle(int pi, int ti)
Convenience method to check if a point is inside a certain triangle.
References GK.DelaunayCalculator.ToTheLeft, GK.DelaunayCalculator.triangles.
Referenced by GK.DelaunayCalculator.FindTriangleNode.
bool GK.DelaunayCalculator.ToTheLeft(int pi, int li0, int li1)
Is the point to the left of the edge?
References GK.DelaunayCalculator.Higher, GK.DelaunayCalculator.verts.
Referenced by GK.DelaunayCalculator.PointInTriangle.