UnityChan::ThirdPersonCamera
float UnityChan.ThirdPersonCamera.smooth
Referenced by UnityChan.ThirdPersonCamera.setCameraPositionJumpView, UnityChan.ThirdPersonCamera.setCameraPositionNormalView.
Transform UnityChan.ThirdPersonCamera.standardPos
Referenced by UnityChan.ThirdPersonCamera.Start.
Transform UnityChan.ThirdPersonCamera.frontPos
Referenced by UnityChan.ThirdPersonCamera.Start.
Transform UnityChan.ThirdPersonCamera.jumpPos
Referenced by UnityChan.ThirdPersonCamera.Start.
bool UnityChan.ThirdPersonCamera.bQuickSwitch
Referenced by UnityChan.ThirdPersonCamera.setCameraPositionFrontView, UnityChan.ThirdPersonCamera.setCameraPositionJumpView, UnityChan.ThirdPersonCamera.setCameraPositionNormalView.
void UnityChan.ThirdPersonCamera.Start()
References UnityChan.ThirdPersonCamera.frontPos, UnityChan.ThirdPersonCamera.jumpPos, UnityChan.ThirdPersonCamera.standardPos.
void UnityChan.ThirdPersonCamera.FixedUpdate()
References UnityChan.ThirdPersonCamera.setCameraPositionFrontView, UnityChan.ThirdPersonCamera.setCameraPositionJumpView, UnityChan.ThirdPersonCamera.setCameraPositionNormalView.
void UnityChan.ThirdPersonCamera.setCameraPositionNormalView()
References UnityChan.ThirdPersonCamera.bQuickSwitch, UnityChan.ThirdPersonCamera.smooth.
Referenced by UnityChan.ThirdPersonCamera.FixedUpdate.
void UnityChan.ThirdPersonCamera.setCameraPositionFrontView()
References UnityChan.ThirdPersonCamera.bQuickSwitch.
Referenced by UnityChan.ThirdPersonCamera.FixedUpdate.
void UnityChan.ThirdPersonCamera.setCameraPositionJumpView()
References UnityChan.ThirdPersonCamera.bQuickSwitch, UnityChan.ThirdPersonCamera.smooth.
Referenced by UnityChan.ThirdPersonCamera.FixedUpdate.