UnityChan::AutoBlink
Status
bool UnityChan.AutoBlink.isActive
Referenced by UnityChan.AutoBlink.LateUpdate.
SkinnedMeshRenderer UnityChan.AutoBlink.ref_SMR_EYE_DEF
SkinnedMeshRenderer UnityChan.AutoBlink.ref_SMR_EL_DEF
float UnityChan.AutoBlink.ratio_Close
Referenced by UnityChan.AutoBlink.SetCloseEyes.
float UnityChan.AutoBlink.ratio_HalfClose
Referenced by UnityChan.AutoBlink.SetHalfCloseEyes.
float UnityChan.AutoBlink.ratio_Open
Referenced by UnityChan.AutoBlink.SetOpenEyes.
float UnityChan.AutoBlink.timeBlink
Referenced by UnityChan.AutoBlink.ResetTimer, UnityChan.AutoBlink.Update.
float UnityChan.AutoBlink.threshold
Referenced by UnityChan.AutoBlink.RandomChange.
float UnityChan.AutoBlink.interval
Referenced by UnityChan.AutoBlink.RandomChange.
bool UnityChan.AutoBlink.timerStarted
Referenced by UnityChan.AutoBlink.ResetTimer, UnityChan.AutoBlink.Update.
bool UnityChan.AutoBlink.isBlink
Referenced by UnityChan.AutoBlink.LateUpdate, UnityChan.AutoBlink.RandomChange.
float UnityChan.AutoBlink.timeRemining
Referenced by UnityChan.AutoBlink.ResetTimer, UnityChan.AutoBlink.Update.
Status UnityChan.AutoBlink.eyeStatus
Referenced by UnityChan.AutoBlink.LateUpdate, UnityChan.AutoBlink.Update.
void UnityChan.AutoBlink.Awake()
void UnityChan.AutoBlink.Start()
References UnityChan.AutoBlink.ResetTimer.
void UnityChan.AutoBlink.ResetTimer()
References UnityChan.AutoBlink.timeBlink, UnityChan.AutoBlink.timeRemining, UnityChan.AutoBlink.timerStarted.
Referenced by UnityChan.AutoBlink.Start, UnityChan.AutoBlink.Update.
void UnityChan.AutoBlink.Update()
References UnityChan.AutoBlink.eyeStatus, UnityChan.AutoBlink.ResetTimer, UnityChan.AutoBlink.timeBlink, UnityChan.AutoBlink.timeRemining, UnityChan.AutoBlink.timerStarted.
void UnityChan.AutoBlink.LateUpdate()
References UnityChan.AutoBlink.eyeStatus, UnityChan.AutoBlink.isActive, UnityChan.AutoBlink.isBlink, UnityChan.AutoBlink.SetCloseEyes, UnityChan.AutoBlink.SetHalfCloseEyes, UnityChan.AutoBlink.SetOpenEyes.
void UnityChan.AutoBlink.SetCloseEyes()
References UnityChan.AutoBlink.ratio_Close.
Referenced by UnityChan.AutoBlink.LateUpdate.
void UnityChan.AutoBlink.SetHalfCloseEyes()
References UnityChan.AutoBlink.ratio_HalfClose.
Referenced by UnityChan.AutoBlink.LateUpdate.
void UnityChan.AutoBlink.SetOpenEyes()
References UnityChan.AutoBlink.ratio_Open.
Referenced by UnityChan.AutoBlink.LateUpdate.
IEnumerator UnityChan.AutoBlink.RandomChange()
References UnityChan.AutoBlink.interval, UnityChan.AutoBlink.isBlink, UnityChan.AutoBlink.threshold.