GK::BreakableSurface
MeshFilter GK.BreakableSurface.Filter
Referenced by GK.BreakableSurface.Reload.
MeshRenderer GK.BreakableSurface.Renderer
Referenced by GK.BreakableSurface.Reload.
MeshCollider GK.BreakableSurface.Collider
Referenced by GK.BreakableSurface.Reload.
Rigidbody GK.BreakableSurface.Rigidbody
Referenced by GK.BreakableSurface.Break, GK.BreakableSurface.Reload.
float GK.BreakableSurface.Area
Referenced by GK.BreakableSurface.Break.
List<Vector2> GK.BreakableSurface.Polygon
Referenced by GK.BreakableSurface.Break, GK.BreakableSurface.Reload.
float GK.BreakableSurface.Thickness
Referenced by GK.BreakableSurface.Break, GK.BreakableSurface.Reload.
float GK.BreakableSurface.MinBreakArea
Referenced by GK.BreakableSurface.Break.
float GK.BreakableSurface.MinImpactToBreak
Referenced by GK.BreakableSurface.OnCollisionEnter.
float GK.BreakableSurface._Area
int GK.BreakableSurface.age
Referenced by GK.BreakableSurface.FixedUpdate, GK.BreakableSurface.OnCollisionEnter, GK.BreakableSurface.Start.
void GK.BreakableSurface.Start()
References GK.BreakableSurface.age, GK.BreakableSurface.Reload.
void GK.BreakableSurface.FixedUpdate()
References GK.BreakableSurface.age.
void GK.BreakableSurface.OnCollisionEnter(Collision coll)
References GK.BreakableSurface.age, GK.BreakableSurface.Break, GK.BreakableSurface.MinImpactToBreak.
void GK.BreakableSurface.Reload()
References GK.BreakableSurface.Collider, GK.BreakableSurface.Filter, GK.BreakableSurface.MeshFromPolygon, GK.BreakableSurface.Polygon, GK.BreakableSurface.Renderer, GK.BreakableSurface.Rigidbody, GK.BreakableSurface.Thickness.
Referenced by GK.BreakableSurface.Start.
void GK.BreakableSurface.Break(Vector2 position)
References GK.BreakableSurface.Area, GK.BreakableSurface.MinBreakArea, GK.BreakableSurface.NormalizedRandom, GK.BreakableSurface.Polygon, GK.BreakableSurface.Rigidbody, GK.BreakableSurface.Thickness.
Referenced by GK.BreakableSurface.OnCollisionEnter.
static float GK.BreakableSurface.NormalizedRandom(float mean, float stddev)
Referenced by GK.BreakableSurface.Break.
static Mesh GK.BreakableSurface.MeshFromPolygon(List< Vector2 > polygon, float thickness)
Referenced by GK.BreakableSurface.Reload.