GK::Geom
static bool GK.Geom.AreCoincident(Vector2 a, Vector2 b)
Are these two vectors (approximately) coincident
Referenced by GK.VoronoiCalculator.CalculateDiagram.
static bool GK.Geom.ToTheLeft(Vector2 p, Vector2 l0, Vector2 l1)
Is point p to the left of the line from l0 to l1?
Referenced by GK.Geom.PointInTriangle, GK.Geom.ToTheRight.
static bool GK.Geom.ToTheRight(Vector2 p, Vector2 l0, Vector2 l1)
Is point p to the right of the line from l0 to l1?
References GK.Geom.ToTheLeft.
static bool GK.Geom.PointInTriangle(Vector2 p, Vector2 c0, Vector2 c1, Vector2 c2)
Is point p inside the triangle formed by c0, c1 and c2 (assuming c1, c2 and c3 are in CCW order)
References GK.Geom.ToTheLeft.
static bool GK.Geom.InsideCircumcircle(Vector2 p, Vector2 c0, Vector2 c1, Vector2 c2)
Is point p inside the circumcircle formed by c0, c1 and c2?
Referenced by GK.DelaunayTriangulation.Verify.
static Vector2 GK.Geom.RotateRightAngle(Vector2 v)
Rotate vector v left 90 degrees
Referenced by GK.Geom.CircumcircleCenter.
static bool GK.Geom.LineLineIntersection(Vector2 p0, Vector2 v0, Vector2 p1, Vector2 v1, out float m0, out float m1)
General line/line intersection method. Each line is defined by a two vectors, a point on the line (p0 and p1 for the two lines) and a direction vector (v0 and v1 for the two lines). The returned value indicates whether the lines intersect. m0 and m1 are the coefficients of how much you have to multiply the direction vectors to get to the intersection.
In other words, if the intersection is located at X, then: X = p0 + m0 * v0 X = p1 + m1 * v1 By checking the m0/m1 values, you can check intersections for line segments and rays.
Referenced by GK.Geom.LineLineIntersection.
static Vector2 GK.Geom.LineLineIntersection(Vector2 p0, Vector2 v0, Vector2 p1, Vector2 v1)
Returns the intersections of two lines. p0/p1 are points on the line, v0/v1 are the direction vectors for the lines.
If there are no intersections, returns a NaN vector
References GK.Geom.LineLineIntersection.
static Vector2 GK.Geom.CircumcircleCenter(Vector2 c0, Vector2 c1, Vector2 c2)
Returns the center of the circumcircle defined by three points (c0, c1 and c2) on its edge.
References GK.Geom.RotateRightAngle.
static Vector2 GK.Geom.TriangleCentroid(Vector2 c0, Vector2 c1, Vector2 c2)
Returns the triangle centroid for triangle defined by points c0, c1 and c2.
static float GK.Geom.Area(IList< Vector2 > polygon)
Returns the signed area of a polygon. CCW polygons return a positive area, CW polygons return a negative area.