SNAP::PackageChecker
ListRequest SNAP.PackageChecker.listRequest
Referenced by SNAP.PackageChecker.CheckPackage.
List<PackageEntry> SNAP.PackageChecker.packageToAdd
Referenced by SNAP.PackageChecker.CheckPackage.
AddRequest [] SNAP.PackageChecker.addRequests
Referenced by SNAP.PackageChecker.CheckPackage.
bool [] SNAP.PackageChecker.installRequired
Referenced by SNAP.PackageChecker.CheckPackage.
string SNAP.PackageChecker.PackageKeyword
Referenced by SNAP.PackageChecker.ReimportPackagesByKeyword.
static void SNAP.PackageChecker.CheckPackage()
References SNAP.PackageChecker.addRequests, SNAP.PackageChecker.GreaterThan, SNAP.PackageChecker.installRequired, SNAP.PackageChecker.InstallSelectedPackage, SNAP.PackageChecker.listRequest, SNAP.PackageChecker.packageToAdd, SNAP.PackageChecker.ReimportPackagesByKeyword.
static AddRequest SNAP.PackageChecker.InstallSelectedPackage(string packageName, string packageVersion)
Referenced by SNAP.PackageChecker.CheckPackage.
static void SNAP.PackageChecker.ReimportPackagesByKeyword()
References SNAP.PackageChecker.PackageKeyword.
Referenced by SNAP.PackageChecker.CheckPackage.
static bool SNAP.PackageChecker.GreaterThan(string versionA, string versionB)
Referenced by SNAP.PackageChecker.CheckPackage.