ReadmeEditor
string ReadmeEditor.kShowedReadmeSessionStateName
Referenced by SelectReadmeAutomatically.
float ReadmeEditor.kSpace
Referenced by OnInspectorGUI.
bool ReadmeEditor.m_Initialized
GUIStyle ReadmeEditor.m_LinkStyle
GUIStyle ReadmeEditor.m_TitleStyle
GUIStyle ReadmeEditor.m_HeadingStyle
GUIStyle ReadmeEditor.m_BodyStyle
GUIStyle ReadmeEditor.LinkStyle
Referenced by LinkLabel.
GUIStyle ReadmeEditor.TitleStyle
Referenced by OnHeaderGUI.
GUIStyle ReadmeEditor.HeadingStyle
Referenced by OnInspectorGUI.
GUIStyle ReadmeEditor.BodyStyle
Referenced by OnInspectorGUI.
static ReadmeEditor.ReadmeEditor()
References SelectReadmeAutomatically.
static void ReadmeEditor.SelectReadmeAutomatically()
References kShowedReadmeSessionStateName, LoadLayout, SelectReadme.
Referenced by ReadmeEditor.
static void ReadmeEditor.LoadLayout()
Referenced by SelectReadmeAutomatically.
static Readme ReadmeEditor.SelectReadme()
Referenced by SelectReadmeAutomatically.
override void ReadmeEditor.OnHeaderGUI()
References Init, TitleStyle.
override void ReadmeEditor.OnInspectorGUI()
References BodyStyle, HeadingStyle, Init, kSpace, LinkLabel.
void ReadmeEditor.Init()
Referenced by OnHeaderGUI, OnInspectorGUI.
bool ReadmeEditor.LinkLabel(GUIContent label, params GUILayoutOption[] options)
References LinkStyle.
Referenced by OnInspectorGUI.