MeshCutterManager
List<GameObject> MeshCutterManager.CutTrackerS1
Referenced by RecursivelyCutCoroutine.
List<GameObject> MeshCutterManager.CutTrackerS2
Referenced by RecursivelyCutCoroutine.
void MeshCutterManager.DamageMesh(GameObject toDamage, float impactForce)
References MonoSingleton< T >.Instance, RecursivelyCutCoroutine.
IEnumerator MeshCutterManager.RecursivelyCutCoroutine(GameObject toCut, int MaxCuts)
References CutTrackerS1, CutTrackerS2, RandomCut, RecursivelyCutSubCoroutine.
Referenced by DamageMesh.
IEnumerator MeshCutterManager.RecursivelyCutSubCoroutine(GameObject toCut, int MaxCuts, List< GameObject > CutTracker)
References RecursivelyCut.
Referenced by RecursivelyCutCoroutine.
void MeshCutterManager.RecursivelyCut(GameObject toCut, int MaxCuts, List< GameObject > CutTracker)
References RandomCut.
Referenced by RecursivelyCutSubCoroutine.
GameObject MeshCutterManager.RandomCut(GameObject toCut)
Referenced by RecursivelyCut, RecursivelyCutCoroutine.
void MeshCutterManager.DeleteTriangle(int index, GameObject obj)