NvMesh
static void NvMesh._Mesh_Release(IntPtr mesh)
Referenced by Release.
static void NvMesh._Mesh_getVertices(IntPtr mesh, [In, Out] Vector3[] arr)
Referenced by getVertices.
static void NvMesh._Mesh_getNormals(IntPtr mesh, [In, Out] Vector3[] arr)
Referenced by getNormals.
static void NvMesh._Mesh_getIndexes(IntPtr mesh, [In, Out] int[] arr)
Referenced by getIndexes.
static void NvMesh._Mesh_getUVs(IntPtr mesh, [In, Out] Vector2[] arr)
Referenced by getUVs.
static int NvMesh._Mesh_getVerticesCount(IntPtr mesh)
Referenced by getVerticesCount.
static int NvMesh._Mesh_getIndexesCount(IntPtr mesh)
Referenced by getIndexesCount.
static IntPtr NvMesh.NvBlastExtAuthoringCreateMesh(Vector3[] positions, Vector3[] normals, Vector2[] uv, Int32 verticesCount, Int32[] indices, Int32 indicesCount)
Referenced by NvMesh.
NvMesh.NvMesh(IntPtr mesh)
References DisposablePtr.Initialize.
NvMesh.NvMesh(Vector3[] positions, Vector3[] normals, Vector2[] uv, Int32 verticesCount, Int32[] indices, Int32 indicesCount)
References DisposablePtr.Initialize, NvBlastExtAuthoringCreateMesh.
Vector3 [] NvMesh.getVertices()
References _Mesh_getVertices, getVerticesCount, DisposablePtr.ptr.
Referenced by toUnityMesh.
Vector3 [] NvMesh.getNormals()
References _Mesh_getNormals, getVerticesCount, DisposablePtr.ptr.
Referenced by toUnityMesh.
Vector2 [] NvMesh.getUVs()
References _Mesh_getUVs, getVerticesCount, DisposablePtr.ptr.
Referenced by toUnityMesh.
int [] NvMesh.getIndexes()
References _Mesh_getIndexes, getIndexesCount, DisposablePtr.ptr.
Referenced by toUnityMesh.
int NvMesh.getVerticesCount()
References _Mesh_getVerticesCount, DisposablePtr.ptr.
Referenced by getNormals, getUVs, getVertices.
int NvMesh.getIndexesCount()
References _Mesh_getIndexesCount, DisposablePtr.ptr.
Referenced by getIndexes.
Mesh NvMesh.toUnityMesh()
References getIndexes, getNormals, getUVs, getVertices.
override void NvMesh.Release()
References _Mesh_Release, DisposablePtr.ptr.