Pause
GameObject Pause.Pause_Panel
Referenced by Pause_Start.
RectTransform Pause.Pause_Cursor
int Pause.Menu_Num
Referenced by Pause_Select.
int Pause.Pause_EndNum
Referenced by Pause_End.
RectTransform Pause.Pause_EndCursor
bool Pause.End_flg
Referenced by Pause_End, Pause_Select.
AudioSource Pause.BGM
AudioClip [] Pause.se
Referenced by Pause_End, Pause_Select, Pause_Start.
bool Pause.Push_Flg
Referenced by Pause_End, Pause_Select.
bool Pause.Select_flg
Referenced by Pause_Select, Pause_Start, Update.
GameObject Pause.Pause_EndPanel
Referenced by Pause_End.
AudioSource Pause.SE
Referenced by Start.
bool Pause.Clear
Referenced by Update.
bool Pause.GameOver
Referenced by Update.
void Pause.Start()
References SE.
void Pause.Update()
References Clear, GameOver, Pause_Select, Pause_Start, Select_flg.
void Pause.Pause_Start()
References Pause_Panel, se, Select_flg.
Referenced by Update.
void Pause.Pause_Select()
References End_flg, Menu_Num, Pause_End, Push_Flg, se, Select_flg.
Referenced by Update.
void Pause.Pause_End()
References End_flg, Pause_EndNum, Pause_EndPanel, Push_Flg, se.
Referenced by Pause_Select.