CFXEasyEditor
CFXEasyEditor CFXEasyEditor.SingleWindow
int CFXEasyEditor.SelectedParticleSystemsCount
Referenced by OnGUI, UpdateSelectionCount.
bool CFXEasyEditor.AffectAlpha
Referenced by applyColor, OnGUI.
Color CFXEasyEditor.ColorValue
Referenced by applyColor, OnGUI.
Color CFXEasyEditor.ColorValue2
Referenced by applyColor, OnGUI.
float CFXEasyEditor.ScalingValue
Referenced by applyScale, OnGUI, ScaleParticleValues.
float CFXEasyEditor.LTScalingValue
Referenced by applySpeed, OnGUI.
float CFXEasyEditor.DelayValue
Referenced by applyDelay, OnGUI.
float CFXEasyEditor.DurationValue
Referenced by applyDuration, OnGUI.
bool CFXEasyEditor.TintStartColor
Referenced by addLightness, hueShift, OnGUI, tintColor.
bool CFXEasyEditor.TintColorModule
Referenced by addLightness, hueShift, OnGUI, tintColor.
bool CFXEasyEditor.TintColorSpeedModule
Referenced by addLightness, hueShift, OnGUI, tintColor.
Color CFXEasyEditor.TintColorValue
Referenced by OnGUI, tintColor.
float CFXEasyEditor.TintHueShiftValue
Referenced by hueShift, OnGUI.
int CFXEasyEditor.LightnessStep
Referenced by addLightness.
ParticleSystem CFXEasyEditor.sourceObject
Referenced by OnGUI, RefreshCurrentlyEnabledModules.
ParticleSystemModule [] CFXEasyEditor.modulesToCopy
Referenced by CopyModules, OnGUI, RefreshCurrentlyEnabledModules.
bool CFXEasyEditor.basicFoldout
Referenced by OnDisable, OnEnable, OnGUI.
bool CFXEasyEditor.colorFoldout
Referenced by OnDisable, OnEnable, OnGUI.
bool CFXEasyEditor.copyFoldout
Referenced by OnDisable, OnEnable, OnGUI.
bool CFXEasyEditor.foldoutChanged
Referenced by OnGUI, RefreshCurrentlyEnabledModules.
bool CFXEasyEditor.pref_ShowAsToolbox
Referenced by OnEnable, OnGUI.
bool CFXEasyEditor.pref_IncludeChildren
Referenced by addLightness, applyColor, applyDelay, applyDuration, applyScale, applySpeed, hueShift, loopEffect, OnEnable, OnGUI, prewarmEffect, tintColor, UpdateSelectionCount.
bool CFXEasyEditor.pref_HideDisabledModulesCopy
Referenced by GUISelectModule, OnEnable, OnGUI.
bool CFXEasyEditor.needSpace
Referenced by GUISelectModule, SelectModulesSpace.
string [] CFXEasyEditor.PropertiesToScale
Referenced by ScaleParticleValues.
GUIStyle CFXEasyEditor._LineStyle
GUIStyle CFXEasyEditor.LineStyle
Referenced by GUILine.
static void CFXEasyEditor.ShowWindow()
void CFXEasyEditor.OnEnable()
References basicFoldout, colorFoldout, copyFoldout, pref_HideDisabledModulesCopy, pref_IncludeChildren, pref_ShowAsToolbox, RefreshCurrentlyEnabledModules.
void CFXEasyEditor.OnFocus()
References RefreshCurrentlyEnabledModules.
void CFXEasyEditor.OnSelectionChange()
References UpdateSelectionCount.
void CFXEasyEditor.OnDisable()
References basicFoldout, colorFoldout, copyFoldout.
void CFXEasyEditor.UpdateSelectionCount()
References pref_IncludeChildren, SelectedParticleSystemsCount.
Referenced by OnGUI, OnSelectionChange.
void CFXEasyEditor.OnGUI()
References AffectAlpha, applyColor, applyDelay, applyDuration, applyScale, applySpeed, basicFoldout, colorFoldout, ColorValue, ColorValue2, copyFoldout, CopyModules, DelayValue, DurationValue, foldoutChanged, GUISelectModule, GUISeparator, hueShift, loopEffect, LTScalingValue, modulesToCopy, pref_HideDisabledModulesCopy, pref_IncludeChildren, pref_ShowAsToolbox, prewarmEffect, RefreshCurrentlyEnabledModules, ScalingValue, SelectedParticleSystemsCount, SelectModulesSpace, sourceObject, tintColor, TintColorModule, TintColorSpeedModule, TintColorValue, TintHueShiftValue, TintStartColor, UpdateSelectionCount.
void CFXEasyEditor.RefreshCurrentlyEnabledModules()
References foldoutChanged, modulesToCopy, sourceObject.
Referenced by OnEnable, OnFocus, OnGUI.
void CFXEasyEditor.SelectModulesSpace()
References needSpace.
Referenced by OnGUI.
void CFXEasyEditor.GUISelectModule(ParticleSystemModule module)
References CFXEasyEditor.ParticleSystemModule.enabledInSource, needSpace, pref_HideDisabledModulesCopy.
Referenced by OnGUI.
void CFXEasyEditor.loopEffect(bool setLoop)
References pref_IncludeChildren.
Referenced by OnGUI.
void CFXEasyEditor.prewarmEffect(bool setPrewarm)
References pref_IncludeChildren.
Referenced by OnGUI.
void CFXEasyEditor.applyScale()
References pref_IncludeChildren, ScaleParticleValues, ScalingValue.
Referenced by OnGUI.
void CFXEasyEditor.applyColor()
References AffectAlpha, ColorValue, ColorValue2, pref_IncludeChildren.
Referenced by OnGUI.
void CFXEasyEditor.tintColor()
References GenericTintColorProperty, pref_IncludeChildren, TintColorModule, TintColorSpeedModule, TintColorValue, TintStartColor.
Referenced by OnGUI.
void CFXEasyEditor.hueShift()
References GenericTintColorProperty, pref_IncludeChildren, TintColorModule, TintColorSpeedModule, TintHueShiftValue, TintStartColor.
Referenced by OnGUI.
void CFXEasyEditor.GenericTintColorProperty(SerializedProperty colorProperty, float hue, bool shift)
References CFXEasyEditor.HSLColor.FromRGBA, TintGradient.
Referenced by hueShift, tintColor.
void CFXEasyEditor.TintGradient(SerializedProperty gradientProperty, float hue, bool shift)
References CFXEasyEditor.HSLColor.FromRGBA.
Referenced by GenericTintColorProperty.
void CFXEasyEditor.addLightness(bool substract)
References GenericAddLightness, LightnessStep, pref_IncludeChildren, TintColorModule, TintColorSpeedModule, TintStartColor.
void CFXEasyEditor.GenericAddLightness(SerializedProperty colorProperty, float lightness)
References AddLightnessGradient, CFXEasyEditor.HSLColor.FromRGBA.
Referenced by addLightness.
void CFXEasyEditor.AddLightnessGradient(SerializedProperty gradientProperty, float lightness)
References CFXEasyEditor.HSLColor.FromRGBA.
Referenced by GenericAddLightness.
void CFXEasyEditor.applySpeed()
References LTScalingValue, pref_IncludeChildren.
Referenced by OnGUI.
void CFXEasyEditor.applyDuration()
References DurationValue, pref_IncludeChildren.
Referenced by OnGUI.
void CFXEasyEditor.applyDelay()
References DelayValue, pref_IncludeChildren.
Referenced by OnGUI.
void CFXEasyEditor.CopyModules(ParticleSystem source, ParticleSystem dest)
References GenericModuleCopy, modulesToCopy, SubModuleCopy.
Referenced by OnGUI.
void CFXEasyEditor.GenericModuleCopy(SerializedProperty ss, SerializedProperty sd, bool depthBreak=true)
References copyGradient.
Referenced by CopyModules.
void CFXEasyEditor.copyGradient(SerializedProperty ss, SerializedProperty sd)
Referenced by GenericModuleCopy.
void CFXEasyEditor.SubModuleCopy(SerializedObject source, SerializedObject dest)
Referenced by CopyModules.
void CFXEasyEditor.ScaleParticleValues(ParticleSystem ps, GameObject parent)
References PropertiesToScale, ScalingValue.
Referenced by applyScale.
void CFXEasyEditor.GUISeparator()
References GUILine.
Referenced by OnGUI.
static void CFXEasyEditor.GUILine(Color color, float height=2f)
References LineStyle.
Referenced by GUISeparator.