WFX_Demo_New
Renderer WFX_Demo_New.groundRenderer
Collider WFX_Demo_New.groundCollider
Referenced by Update.
Image WFX_Demo_New.slowMoBtn
Text WFX_Demo_New.slowMoLabel
Image WFX_Demo_New.camRotBtn
Text WFX_Demo_New.camRotLabel
Image WFX_Demo_New.groundBtn
Text WFX_Demo_New.groundLabel
Text WFX_Demo_New.EffectLabel
Text WFX_Demo_New.EffectIndexLabel
GameObject [] WFX_Demo_New.AdditionalEffects
Referenced by Awake.
GameObject WFX_Demo_New.ground
GameObject WFX_Demo_New.walls
GameObject WFX_Demo_New.bulletholes
GameObject WFX_Demo_New.m4
Material WFX_Demo_New.wood
Referenced by selectMaterial.
Material WFX_Demo_New.woodWall
Referenced by selectMaterial.
GameObject WFX_Demo_New.m4fps
Referenced by showHideStuff.
Material WFX_Demo_New.concrete
Referenced by selectMaterial.
Material WFX_Demo_New.metal
Referenced by selectMaterial.
Material WFX_Demo_New.checker
Referenced by selectMaterial.
Material WFX_Demo_New.concreteWall
Referenced by selectMaterial.
Material WFX_Demo_New.metalWall
Referenced by selectMaterial.
Material WFX_Demo_New.checkerWall
Referenced by selectMaterial.
string WFX_Demo_New.groundTextureStr
Referenced by nextTexture, prevTexture, selectMaterial, showHideStuff.
List<string> WFX_Demo_New.groundTextures
Referenced by nextTexture, prevTexture.
GameObject [] WFX_Demo_New.ParticleExamples
Referenced by Awake, nextParticle, showHideStuff, spawnParticle, UpdateUI.
int WFX_Demo_New.exampleIndex
Referenced by nextParticle, prevParticle, showHideStuff, spawnParticle, UpdateUI.
bool WFX_Demo_New.slowMo
Referenced by OnToggleSlowMo.
Vector3 WFX_Demo_New.defaultCamPosition
Referenced by Awake, Update.
Quaternion WFX_Demo_New.defaultCamRotation
Referenced by Awake, Update.
List<GameObject> WFX_Demo_New.onScreenParticles
Referenced by CheckForDeletedParticles, destroyParticles.
void WFX_Demo_New.Awake()
References AdditionalEffects, defaultCamPosition, defaultCamRotation, ParticleExamples, UpdateUI.
void WFX_Demo_New.Update()
References defaultCamPosition, defaultCamRotation, destroyParticles, groundCollider, nextParticle, prevParticle, spawnParticle.
void WFX_Demo_New.UpdateUI()
References exampleIndex, ParticleExamples.
Referenced by Awake, nextParticle, prevParticle.
IEnumerator WFX_Demo_New.CheckForDeletedParticles()
References onScreenParticles.
void WFX_Demo_New.prevParticle()
References exampleIndex, showHideStuff, UpdateUI.
Referenced by OnPreviousEffect, Update.
void WFX_Demo_New.nextParticle()
References exampleIndex, ParticleExamples, showHideStuff, UpdateUI.
Referenced by OnNextEffect, Update.
void WFX_Demo_New.destroyParticles()
References onScreenParticles.
Referenced by Update.
void WFX_Demo_New.prevTexture()
References groundTextures, groundTextureStr, selectMaterial.
void WFX_Demo_New.nextTexture()
References groundTextures, groundTextureStr, selectMaterial.
void WFX_Demo_New.selectMaterial()
References checker, checkerWall, concrete, concreteWall, groundTextureStr, metal, metalWall, wood, woodWall.
Referenced by nextTexture, prevTexture, showHideStuff.
void WFX_Demo_New.showHideStuff()
References exampleIndex, groundTextureStr, m4fps, ParticleExamples, selectMaterial.
Referenced by nextParticle, prevParticle.
void WFX_Demo_New.OnToggleGround()
void WFX_Demo_New.OnToggleCamera()
References CFX_Demo_RotateCamera.rotating.
void WFX_Demo_New.OnToggleSlowMo()
References slowMo.
void WFX_Demo_New.OnPreviousEffect()
References prevParticle.
void WFX_Demo_New.OnNextEffect()
References nextParticle.
GameObject WFX_Demo_New.spawnParticle()
References exampleIndex, ParticleExamples.
Referenced by Update.