UnityChan::SpringManager
float UnityChan.SpringManager.dynamicRatio
Referenced by UnityChan.SpringManager.LateUpdate, UnityChan.SpringManager.Update.
float UnityChan.SpringManager.stiffnessForce
Referenced by UnityChan.SpringManager.UpdateParameters.
AnimationCurve UnityChan.SpringManager.stiffnessCurve
Referenced by UnityChan.SpringManager.UpdateParameters.
float UnityChan.SpringManager.dragForce
Referenced by UnityChan.SpringManager.UpdateParameters.
AnimationCurve UnityChan.SpringManager.dragCurve
Referenced by UnityChan.SpringManager.UpdateParameters.
SpringBone [] UnityChan.SpringManager.springBones
Referenced by UnityChan.SpringManager.LateUpdate, UnityChan.SpringManager.UpdateParameter.
void UnityChan.SpringManager.Start()
References UnityChan.SpringManager.UpdateParameters.
void UnityChan.SpringManager.Update()
References UnityChan.SpringManager.dynamicRatio, UnityChan.SpringManager.UpdateParameters.
void UnityChan.SpringManager.LateUpdate()
References UnityChan.SpringManager.dynamicRatio, UnityChan.SpringManager.springBones.
void UnityChan.SpringManager.UpdateParameters()
References UnityChan.SpringManager.dragCurve, UnityChan.SpringManager.dragForce, UnityChan.SpringManager.stiffnessCurve, UnityChan.SpringManager.stiffnessForce, UnityChan.SpringManager.UpdateParameter.
Referenced by UnityChan.SpringManager.Start, UnityChan.SpringManager.Update.
void UnityChan.SpringManager.UpdateParameter(string fieldName, float baseValue, AnimationCurve curve)
References UnityChan.SpringManager.springBones.
Referenced by UnityChan.SpringManager.UpdateParameters.