PlayerController
CharacterController PlayerController.cCon
Referenced by Start.
Vector3 PlayerController.velocity
Referenced by Update.
Animator PlayerController.animator
Referenced by Start.
float PlayerController.walkSpeed
Referenced by Update.
float PlayerController.runSpeed
Referenced by Update.
bool PlayerController.runFlag
Referenced by Update.
Transform PlayerController.myCamera
Referenced by Start.
float PlayerController.cameraRotateLimit
Referenced by RotateCamera.
bool PlayerController.cameraRotForward
Referenced by RotateCamera.
Quaternion PlayerController.initCameraRot
Referenced by Start.
float PlayerController.rotateSpeed
Referenced by RotateCamera, RotateChara.
float PlayerController.xRotate
Referenced by RotateCamera.
float PlayerController.yRotate
Referenced by RotateChara.
float PlayerController.RstickSpeed
Referenced by RotateCamera, RotateChara.
Quaternion PlayerController.charaRotate
Referenced by RotateChara, Start.
Quaternion PlayerController.cameraRotate
Referenced by RotateCamera, Start.
bool PlayerController.charaRotFlag
Referenced by RotateChara.
float PlayerController.jumpPower
Referenced by Update.
float PlayerController.dashJumpPower
Referenced by Update.
bool PlayerController.jump
Referenced by Update.
bool PlayerController.Attack
Rigidbody PlayerController.rb
Referenced by Start.
Image PlayerController.GameOver
bool PlayerController.jumpFlg
Referenced by GetjumpFlg, Start.
bool PlayerController.ContinueFlg
Referenced by continueflg, GameOverCoroutine, Start.
bool PlayerController.GameOverFlg
Referenced by GetGameOverFlg, OnParticleCollision, Start.
Text PlayerController.YouDead
Text PlayerController.Continue
Text PlayerController.BombDead
Text PlayerController.Yes
Text PlayerController.No
float PlayerController.GameOverCount
Referenced by GameOverCoroutine, OnParticleCollision.
GameObject PlayerController.BGM
AudioSource PlayerController.Dead
void PlayerController.Start()
References animator, cameraRotate, cCon, charaRotate, ContinueFlg, GameOverFlg, initCameraRot, jumpFlg, myCamera, rb.
void PlayerController.Update()
References dashJumpPower, jump, jumpPower, RotateCamera, RotateChara, runFlag, runSpeed, velocity, walkSpeed.
void PlayerController.RotateChara()
References charaRotate, charaRotFlag, rotateSpeed, RstickSpeed, yRotate.
Referenced by Update.
void PlayerController.RotateCamera()
References cameraRotate, cameraRotateLimit, cameraRotForward, rotateSpeed, RstickSpeed, xRotate.
Referenced by Update.
void PlayerController.OnParticleCollision(GameObject other)
References GameOverCoroutine, GameOverCount, GameOverFlg.
IEnumerator PlayerController.GameOverCoroutine()
References ContinueFlg, GameOverCount.
Referenced by OnParticleCollision.
static bool PlayerController.continueflg()
References ContinueFlg.
static bool PlayerController.GetGameOverFlg()
References GameOverFlg.
static bool PlayerController.GetjumpFlg()
References jumpFlg.
Referenced by Walk.OnControllerColliderHit.