WFX_Demo
float WFX_Demo.cameraSpeed
Referenced by Update.
bool WFX_Demo.orderedSpawns
Referenced by RandomSpawnsCoroutine.
float WFX_Demo.step
Referenced by RandomSpawnsCoroutine.
float WFX_Demo.range
Referenced by RandomSpawnsCoroutine.
GameObject WFX_Demo.walls
Referenced by showHideStuff.
GameObject WFX_Demo.bulletholes
GameObject [] WFX_Demo.ParticleExamples
Referenced by nextParticle, OnGUI, showHideStuff, spawnParticle.
Material WFX_Demo.wood
Referenced by selectMaterial.
Material WFX_Demo.woodWall
Referenced by selectMaterial.
GameObject WFX_Demo.m4
Referenced by OnGUI, showHideStuff.
float WFX_Demo.order
Referenced by RandomSpawnsCoroutine.
int WFX_Demo.exampleIndex
Referenced by nextParticle, OnGUI, prevParticle, showHideStuff, spawnParticle.
string WFX_Demo.randomSpawnsDelay
Referenced by RandomSpawnsCoroutine.
bool WFX_Demo.randomSpawns
bool WFX_Demo.slowMo
Referenced by OnGUI.
bool WFX_Demo.rotateCam
Referenced by OnGUI, Update.
Material WFX_Demo.concrete
Referenced by selectMaterial.
Material WFX_Demo.metal
Referenced by selectMaterial.
Material WFX_Demo.checker
Referenced by selectMaterial.
Material WFX_Demo.concreteWall
Referenced by selectMaterial.
Material WFX_Demo.metalWall
Referenced by selectMaterial.
Material WFX_Demo.checkerWall
Referenced by selectMaterial.
string WFX_Demo.groundTextureStr
Referenced by nextTexture, OnGUI, prevTexture, selectMaterial, showHideStuff.
List<string> WFX_Demo.groundTextures
Referenced by nextTexture, prevTexture.
GameObject WFX_Demo.m4fps
Referenced by showHideStuff.
bool WFX_Demo.rotate_m4
Referenced by OnGUI, Update.
void WFX_Demo.OnMouseDown()
References spawnParticle.
void WFX_Demo.SetActiveCrossVersions(GameObject obj, bool active)
Referenced by showHideStuff, spawnParticle.
void WFX_Demo.OnGUI()
References exampleIndex, groundTextureStr, m4, nextParticle, nextTexture, ParticleExamples, prevParticle, prevTexture, rotate_m4, rotateCam, slowMo.
IEnumerator WFX_Demo.RandomSpawnsCoroutine()
References order, orderedSpawns, randomSpawnsDelay, range, spawnParticle, step.
void WFX_Demo.Update()
References cameraSpeed, nextParticle, prevParticle, rotate_m4, rotateCam.
void WFX_Demo.prevTexture()
References groundTextures, groundTextureStr, selectMaterial.
Referenced by OnGUI.
void WFX_Demo.nextTexture()
References groundTextures, groundTextureStr, selectMaterial.
Referenced by OnGUI.
void WFX_Demo.selectMaterial()
References checker, checkerWall, concrete, concreteWall, groundTextureStr, metal, metalWall, wood, woodWall.
Referenced by nextTexture, prevTexture, showHideStuff.
void WFX_Demo.prevParticle()
References exampleIndex, showHideStuff.
Referenced by OnGUI, Update.
void WFX_Demo.nextParticle()
References exampleIndex, ParticleExamples, showHideStuff.
Referenced by OnGUI, Update.
void WFX_Demo.showHideStuff()
References exampleIndex, groundTextureStr, m4, m4fps, ParticleExamples, selectMaterial, SetActiveCrossVersions, walls.
Referenced by nextParticle, prevParticle.
GameObject WFX_Demo.spawnParticle()
References exampleIndex, ParticleExamples, SetActiveCrossVersions.
Referenced by OnMouseDown, RandomSpawnsCoroutine.