NvMeshCleaner
static void NvMeshCleaner._Cleaner_Release(IntPtr cleaner)
Referenced by Release.
static IntPtr NvMeshCleaner._Cleaner_cleanMesh(IntPtr cleaner, IntPtr mesh)
Referenced by cleanMesh.
static IntPtr NvMeshCleaner.NvBlastExtAuthoringCreateMeshCleaner()
Referenced by NvMeshCleaner.
NvMeshCleaner.NvMeshCleaner()
References DisposablePtr.Initialize, NvBlastExtAuthoringCreateMeshCleaner.
NvMesh NvMeshCleaner.cleanMesh(NvMesh mesh)
References _Cleaner_cleanMesh, DisposablePtr.ptr.
override void NvMeshCleaner.Release()
References _Cleaner_Release, DisposablePtr.ptr.