WaterEditorUtility
static float WaterEditorUtility.GetMaterialFloat(System.String name, Material mat)
Referenced by UnityStandardAssets.Water.SpecularLightingEditor.OnInspectorGUI.
static void WaterEditorUtility.SetMaterialFloat(System.String name, float f, Material mat)
Referenced by UnityStandardAssets.Water.SpecularLightingEditor.OnInspectorGUI.
static Color WaterEditorUtility.GetMaterialColor(System.String name, Material mat)
Referenced by UnityStandardAssets.Water.SpecularLightingEditor.OnInspectorGUI.
static void WaterEditorUtility.SetMaterialColor(System.String name, Color color, Material mat)
Referenced by UnityStandardAssets.Water.SpecularLightingEditor.OnInspectorGUI.
static Vector4 WaterEditorUtility.GetMaterialVector(System.String name, Material mat)
static void WaterEditorUtility.SetMaterialVector(System.String name, Vector4 vector, Material mat)
static Texture WaterEditorUtility.GetMaterialTexture(System.String theName, Material mat)
Referenced by UnityStandardAssets.Water.WaterBaseEditor.OnInspectorGUI.
static void WaterEditorUtility.SetMaterialTexture(System.String theName, Texture parameter, Material mat)
static Material WaterEditorUtility.LocateValidWaterMaterial(Transform parent)
Referenced by UnityStandardAssets.Water.WaterBaseEditor.OnInspectorGUI.
static void WaterEditorUtility.CurveGui(System.String name, SerializedObject serObj, Color color)