CFXEasyEditor::HSLColor
float CFXEasyEditor.HSLColor.h
Referenced by CFXEasyEditor.HSLColor.ColorWithHue, CFXEasyEditor.HSLColor.FromRGBA, CFXEasyEditor.HSLColor.HSLColor, CFXEasyEditor.HSLColor.ToRGBA.
float CFXEasyEditor.HSLColor.s
Referenced by CFXEasyEditor.HSLColor.FromRGBA, CFXEasyEditor.HSLColor.HSLColor, CFXEasyEditor.HSLColor.ToRGBA.
float CFXEasyEditor.HSLColor.l
Referenced by CFXEasyEditor.HSLColor.ColorWithLightnessOffset, CFXEasyEditor.HSLColor.FromRGBA, CFXEasyEditor.HSLColor.HSLColor, CFXEasyEditor.HSLColor.ToRGBA.
float CFXEasyEditor.HSLColor.a
Referenced by CFXEasyEditor.HSLColor.FromRGBA, CFXEasyEditor.HSLColor.HSLColor, CFXEasyEditor.HSLColor.ToRGBA.
CFXEasyEditor.HSLColor.HSLColor(float h, float s, float l, float a)
References CFXEasyEditor.HSLColor.a, CFXEasyEditor.HSLColor.h, CFXEasyEditor.HSLColor.l, CFXEasyEditor.HSLColor.s.
Referenced by CFXEasyEditor.HSLColor.FromRGBA.
CFXEasyEditor.HSLColor.HSLColor(float h, float s, float l)
References CFXEasyEditor.HSLColor.h, CFXEasyEditor.HSLColor.l, CFXEasyEditor.HSLColor.s.
CFXEasyEditor.HSLColor.HSLColor(Color c)
References CFXEasyEditor.HSLColor.a, CFXEasyEditor.HSLColor.FromRGBA, CFXEasyEditor.HSLColor.h, CFXEasyEditor.HSLColor.l, CFXEasyEditor.HSLColor.s.
Color CFXEasyEditor.HSLColor.ToRGBA()
References CFXEasyEditor.HSLColor.a, CFXEasyEditor.HSLColor.h, CFXEasyEditor.HSLColor.l, CFXEasyEditor.HSLColor.s, CFXEasyEditor.HSLColor.Value.
Color CFXEasyEditor.HSLColor.VividColor()
Color CFXEasyEditor.HSLColor.ColorWithHue(float hue, bool shift)
References CFXEasyEditor.HSLColor.h.
Color CFXEasyEditor.HSLColor.ColorWithLightnessOffset(float lightness)
References CFXEasyEditor.HSLColor.l.
static HSLColor CFXEasyEditor.HSLColor.FromRGBA(Color c)
References CFXEasyEditor.HSLColor.a, CFXEasyEditor.HSLColor.h, CFXEasyEditor.HSLColor.HSLColor, CFXEasyEditor.HSLColor.l, CFXEasyEditor.HSLColor.s.
Referenced by CFXEasyEditor.AddLightnessGradient, CFXEasyEditor.GenericAddLightness, CFXEasyEditor.GenericTintColorProperty, CFXEasyEditor.HSLColor.HSLColor, CFXEasyEditor.HSLColor.operator HSLColor, CFXEasyEditor.TintGradient.
static float CFXEasyEditor.HSLColor.Value(float n1, float n2, float hue)
Referenced by CFXEasyEditor.HSLColor.ToRGBA.
static implicit CFXEasyEditor.HSLColor.operator HSLColor(Color src)
References CFXEasyEditor.HSLColor.FromRGBA.
static implicit CFXEasyEditor.HSLColor.operator Color(HSLColor src)